apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::824333137275:role/eksctl-roboshop-nodegroup-roboshop-NodeInstanceRole-XEm0CWhdWv6w
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::824333137275:user/srinu
      username: srinu
kind: ConfigMap
metadata:
  creationTimestamp: "2026-03-27T15:58:36Z"
  name: aws-auth
  namespace: kube-system
  uid: a961c14d-e708-46f0-8fd4-412b6d92f4e1
